<?php

namespace ContainerRq0Qppu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\LivreController' shared autowired service.
     *
     * @return \App\Controller\LivreController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/LivreController.php';

        $container->services['App\\Controller\\LivreController'] = $instance = new \App\Controller\LivreController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\LivreRepository'] ?? $container->load('getLivreRepositoryService')), ($container->privates['App\\Repository\\AuteurRepository'] ?? $container->load('getAuteurRepositoryService')), ($container->privates['App\\Repository\\CategorieRepository'] ?? $container->load('getCategorieRepositoryService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\LivreController', $container));

        return $instance;
    }
}
