<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKNBz3He\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKNBz3He/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKNBz3He.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKNBz3He\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKNBz3He\App_KernelDevDebugContainer([
    'container.build_hash' => 'KNBz3He',
    'container.build_id' => '08989d00',
    'container.build_time' => 1760704543,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKNBz3He');
