<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGrEQOCr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGrEQOCr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGrEQOCr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGrEQOCr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGrEQOCr\App_KernelDevDebugContainer([
    'container.build_hash' => 'GrEQOCr',
    'container.build_id' => 'f84095ec',
    'container.build_time' => 1760705819,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGrEQOCr');
