<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHxzFvS0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHxzFvS0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHxzFvS0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHxzFvS0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHxzFvS0\App_KernelDevDebugContainer([
    'container.build_hash' => 'HxzFvS0',
    'container.build_id' => '5a7d2293',
    'container.build_time' => 1760704059,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHxzFvS0');
